# Generated by Django 4.1.1 on 2022-12-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=122)),
                ('Product_img', models.ImageField(upload_to='pics')),
                ('product_desc', models.CharField(max_length=122)),
            ],
        ),
    ]
