# Generated by Django 4.1.1 on 2022-12-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidbro', '0002_rename_product_img_product_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='media/image'),
        ),
    ]
