# Generated by Django 4.1.1 on 2022-12-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidbro', '0005_contact_delete_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
