# Generated by Django 4.1.1 on 2022-12-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidbro', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='contact_comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='contact_phone',
        ),
    ]
